name = "aifi"
compatibility_date = "2024-09-16"

[site]
bucket = "./"

[[routes]]
pattern = "/*"
zone_name = "aifi.pages.dev"

# Build configuration for Cloudflare Pages
[build]
command = ""
publish = "./"

# Environment variables (if needed)
[env.production]
vars = { }