name = "aifi"
compatibility_date = "2024-09-16"
pages_build_output_dir = "./"

# Build configuration for Cloudflare Pages
[build]
command = ""
publish = "./"

# Environment variables (if needed)
[env.production]
vars = { }